services:
  cdn:
    build: .
    container_name: cdn_app
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cdn.rule=Host(${HOST})"
      - "traefik.http.routers.cdn.entrypoints=websecure"
      - "traefik.http.routers.cdn.tls.certresolver=myresolver"
      - "traefik.http.services.cdn.loadbalancer.server.port=8000"
    volumes:
      - cdn-data:/data
networks:
  traefik:
    external: true
volumes:
  cdn-data:
